# -*- coding: utf-8 -*-
"""clean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeblqAEvMp9diFTv4gQKxTopg_2QZK1Z

Importing the neccessary libaries to be use
"""

import numpy as np
import pandas as pd
import matplotlib.pylab as plt

"""loading the dataset"""

filename = "//content/air-quality-data-continuous.csv"

"""Reading the dataset with pandas libary in order to place it into dataframe from CSV file """

df = pd.read_csv(filename, sep=";")

"""Checking the first five input to the dataframe """

df.head(5)

"""Croping or Truncating the data before the year  01 jan 2010"""

df.truncate('1998-02-08', '2010-01-01').head()

"""Checking more details about the data """

df.info

"""saving the the clean data into another CSV file """

df.to_csv('clean.csv') # relative position