# -*- coding: utf-8 -*-
"""crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeblqAEvMp9diFTv4gQKxTopg_2QZK1Z

Importing the neccessary libaries to be use
"""

import numpy as np
import pandas as pd
import matplotlib.pylab as plt

"""loading the dataset"""

filename = "//content/air-quality-data-continuous.csv"

"""Reading the dataset with pandas libary in order to place it into dataframe from CSV file """

df = pd.read_csv(filename, sep=";")

"""Checking the first five input to the dataframe """

df.head(5)

"""Cropping out the SiteID and Location to view if there is no Missing value or mismatch record """

df_new = df[['SiteID', 'Location']]

"""Checking the last value of the crop data """

df_new.tail()

"""Checking the corresponding SiteID"""

df_new.value_counts()

"""check out for missing data , but none is present in the data set """

df_new.isnull().sum()

"""saving the crop data into crop.csv file """

df_new.to_csv('crop.csv') # relative position