# -*- coding: utf-8 -*-
"""insert_100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ntmpJAP-rrpr69P0Ik69CzKCDzUCFMde

importing the neccessary libary to perform the task i.e libary to be use to create a database and dataframe libary
"""

import pandas as pd
import sqlite3

"""Creating the database and the connection """

conn = sqlite3.connect('Insert_100') 
c = conn.cursor()

c.execute('CREATE TABLE IF NOT EXISTS products (SiteID,Location)')
conn.commit()

"""Passing the data set into pandas dataframe  for easy read and convertion """

df = pd.read_csv('/content/air-quality-data-continuous.csv',sep=';')

"""converting the dataframe into an sql file"""

df.to_sql('products', conn, if_exists='replace', index = False)

"""Querying the database to holds 100 insert """

c.execute('''  
		SELECT *
    FROM products
    LIMIT 100;

          ''')

"""converting the data into a pandas dataframe from sql file """

df = pd.DataFrame(c.fetchall())    
print (df)

"""saving the file as sql file"""

df.to_sql('insert_100', conn, if_exists='replace', index = False)