# -*- coding: utf-8 -*-
"""populate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RS-ZKS51ADvowSVf_uselNzR05gzrr9f

Importing the neccessary libary
"""

from sqlalchemy import create_engine
import pandas as pd

"""Inputing the cleaned dataset"""

data = pd.read_csv('/content/clean.csv')

"""Creating db engine(Instance) with the name pollution_db2"""

# Create the db engine
pollution_db2 = create_engine('sqlite:///:memory:')

"""Populating the database instance with the clean.csv created earlier """

# Store the dataframe as a table
data.to_sql('data_table', pollution_db2)

"""quering  the database to know if it is populated with the clean"""

# Query 1 on the relational table
res1 = pd.read_sql_query('SELECT * FROM data_table', pollution_db2)
print('Result 1')
print(res1)
print('')